### ISSUE TITLE
Support to expect multiple requests in one tests

### ISSUE THREAD

**Issue by sleitz** [systemhaus/GuzzleHttpMock#2]
The original functionality makes one feel it should be possible to set up multiple expectations in one test scenario, e.g.:

 * Expect a GET request _/test_
 * Expect a POST request _/test_
 * Expect a GET request _/somewhere_

In fact, this tests does not run through. The counter contained output shows the encountered three requests and maps them to one expected request only: the first of the tree which were set up.

I suspect the expected_count is only for replaying the same request multiple times, not for separate requests in one tests. But sometimes it is necessary for the integrity. We should extend the framework to expect multiple requests in the order in which they were set up, distinguishing between an individual expected_count and a total one.

**Comment by LarsLuz** [comment]
The described problem does actually not exists, there was only a minor misunderstanding
